 
baseURL = "/" # 部署到線上之後要使用的主要域名 = FQDN
defaultContentLanguage = "zh-tw"    # 預設語系
title = "小宇's blog"                # 網站 title
theme = "stack"              # 指定使用的佈景 (與資料夾名稱一樣)
paginate = 7                        # 每頁顯示幾筆文章
canonifyurls = true     
